# Generated by Django 5.2.5 on 2025-09-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_customer_state_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
