# Generated by Django 5.2.5 on 2025-09-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Vidarbha, Marathwada",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("group_name", models.CharField(max_length=200)),
                ("group_link", models.URLField(unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("signal", "Signal"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Community Groups",
                "ordering": ["state", "district", "group_name"],
            },
        ),
    ]
