# Generated by Django 5.2.5 on 2025-09-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_communitygroup_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communitygroup",
            options={},
        ),
        migrations.AlterField(
            model_name="communitygroup",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
