# Generated by Django 5.2.5 on 2025-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_communitygroup_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitygroup",
            name="state",
            field=models.CharField(max_length=50),
        ),
    ]
