# Generated by Django 5.2.6 on 2025-10-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SD', 'Seeds'), ('FT', 'Fertilizers'), ('MC', 'Machinery'), ('EQ', 'Equipment')], max_length=2),
        ),
    ]
