# Generated by Django 5.2.6 on 2025-10-12 11:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_newsletter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communitygroup",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="orderplaced",
            options={"ordering": ["-ordered_date"]},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="communitygroup",
            name="district",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="communitygroup",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="communitygroup",
            name="state",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="ordered_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.payment"
            ),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Packed", "Packed"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Cancel", "Cancel"),
                    ("Pending", "Pending"),
                ],
                db_index=True,
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("SD", "Seeds"),
                    ("FT", "Fertilizers"),
                    ("MC", "Machinery"),
                    ("EQ", "Equipment"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="prodapp",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "discounted_price"],
                name="app_product_categor_d98954_idx",
            ),
        ),
    ]
