# Generated by Django 5.2.6 on 2025-10-12 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_communitygroup_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communitygroup",
            options={},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orderplaced",
            options={},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="app_product_categor_d98954_idx",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="communitygroup",
            name="district",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="communitygroup",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="communitygroup",
            name="state",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="ordered_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="payment",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.payment",
            ),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Packed", "Packed"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Cancel", "Cancel"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("SD", "Seeds"),
                    ("FT", "Fertilizers"),
                    ("MC", "Machinery"),
                    ("EQ", "Equipment"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="prodapp",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
